apiversion: v1
kind: AppConfig
spec:
  db:
    path: ./db
  jwt:
    key: 0qm0sd7cmjo5t9gidrzgctxzd2by3x7y
  server:
    bind:
      host: 0.0.0.0
      port: 8080
    ssl:
      enable: false
  session:
    expires: 24
